- build.gradle
- src/main/java/com/aptner/v3/global/config/SecurityConfig.java
security 인가, 경로설정
비밀번호 암호화를 위한 BCryptPasswordEncoder @Bean 설정
> [#13-security-config] spring security config

- compose.yaml
1. 게시글 조회수
2. Refresh Token 저장
목적의 Redis 서버 도입.
> add redis compose.yml

- src/main/java/com/aptner/v3/board/common/reaction/ReactionController.java
- src/main/java/com/aptner/v3/board/complain/ComplainController.java
- src/main/java/com/aptner/v3/board/market/MarketController.java
- src/main/java/com/aptner/v3/global/config/SwaggerConfig.java
#62 
#64 
#54 
#51 
#53 
#58 
추가 배포 : swagger config 수정
> [정기 배포] 240521-1 

- README.md
> [정기 배포] 240521-2

- src/main/java/com/aptner/v3/global/config/CorsConfig.java
> [hotfix/cors] ãㅣlocalhost:3000 허용

- src/main/java/com/aptner/v3/global/config/CorsConfig.java
> [hotfix/cors] localhost:3000 허용 HTTP 명시

- .github/workflows/build.yaml
- src/main/java/com/aptner/v3/MenuInitializer.java
- src/main/resources/application-dev.yaml
- src/main/resources/application.yaml
1. FE팀 편의를 위해  HIDDEN_DEV 환경변수을 사용하여, (임시) 30일 JWT을 생성 하도록 합니다.
2. build.yaml을 통해 application-hidden-dev.yaml 추가하여 제공합니다.
제거 방법
1. springboot > application.yaml , hidden-dev 제거
```
spring:
profiles:
include: hidden hidden-dev 
```
1. github > setting > secrets > environment secret > hidden_dev 삭제
> [#54-authentication]FE편의를 위해, ACCESS Token 30일

- src/main/java/com/aptner/v3/board/common_post/CommonPostController.java
- src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
- src/main/java/com/aptner/v3/board/complain/Complain.java
- src/main/java/com/aptner/v3/board/complain/ComplainController.java
- src/main/java/com/aptner/v3/board/complain/ComplainService.java
- src/main/java/com/aptner/v3/board/free_post/FreePostService.java
- src/main/java/com/aptner/v3/board/free_post/controller/FreePostController.java
- src/main/java/com/aptner/v3/board/free_post/domain/FreePost.java
- src/main/java/com/aptner/v3/board/market/Market.java
- src/main/java/com/aptner/v3/board/market/MarketController.java
- src/main/java/com/aptner/v3/board/market/MarketService.java
- src/main/java/com/aptner/v3/board/notice_post/NoticePostService.java
- src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostController.java
- src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
- src/main/java/com/aptner/v3/board/qna/Qna.java
- src/main/java/com/aptner/v3/board/qna/QnaController.java
- src/main/java/com/aptner/v3/board/qna/QnaService.java
> @Qulifier 적용

- src/main/java/com/aptner/v3/board/common_post/CommonPostDto.java
- src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
- src/main/java/com/aptner/v3/board/complain/Complain.java
- src/main/java/com/aptner/v3/board/complain/dto/ComplainDto.java
- src/main/java/com/aptner/v3/board/free_post/domain/FreePost.java
- src/main/java/com/aptner/v3/board/free_post/dto/FreePostDto.java
- src/main/java/com/aptner/v3/board/market/Market.java
- src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
- src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
- src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
- src/main/java/com/aptner/v3/board/qna/Qna.java
- src/main/java/com/aptner/v3/board/qna/dto/QnaDto.java
게시판 항목 :  add imageurls , categoryId
> [긴급배포] add imageurls , categoryId

- src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillController.java
> [hotfix] 관리비 upload enable

- src/main/java/com/aptner/v3/global/config/SwaggerConfig.java
> [hotfix] swagger config

- src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillService.java
- src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/MaintenanceBillSummaryDto.java
- src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/SquareOnSquareInfoDto.java
1. 관리비 요약: 감면 금액 Total 반환
2. 관리비 요약: 요청 날짜 반환
3. 동일면적 대비: 누락된 평균 금액 추가
> refactor: 관리비 Response 개선

- src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
- src/main/java/com/aptner/v3/board/free_post/FreePostService.java
- src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
- src/main/java/com/aptner/v3/board/qna/dto/QnaDto.java
> 검색어 -> 인기 게시글 같이 노출 (해결 완료)

- src/main/java/com/aptner/v3/board/qna/QnaController.java
> ëqna 삭제 오류

- src/main/java/com/aptner/v3/board/market/MarketService.java
- src/main/java/com/aptner/v3/global/jwt/JwtFilter.java
> [bug fix] 기본 user 정보 변경, 마켓 삭제 수정

- src/main/java/com/aptner/v3/board/market/MarketService.java
- src/main/java/com/aptner/v3/board/qna/QnaController.java
- src/main/java/com/aptner/v3/global/jwt/JwtFilter.java
> [정기배포] 240607

- src/main/java/com/aptner/v3/board/common_post/PostSpecification.java
- src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
- src/main/java/com/aptner/v3/board/free_post/FreePostService.java
- src/test/java/com/aptner/v3/board/common_post/controller/FreePostControllerTest.java
> [bug-fix] 자유게시판 인기글이 없는 경우

- src/main/java/com/aptner/v3/board/free_post/FreePostService.java
- src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillController.java
- src/main/resources/application.yaml
- src/test/resources/application.yaml
> [infra] prod 환경, mysql로 변경

- src/main/java/com/aptner/v3/MenuInitializer.java
- src/main/resources/application.yaml
> [정기배포] 240610

- src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
- src/main/resources/application.yaml
> [New 아이콘] 14일 -> 48시간

- src/main/java/com/aptner/v3/board/comment/CommentService.java
- src/main/java/com/aptner/v3/board/common/reaction/ReactionRepository.java
> [댓글 오류] reaction 검색 오류

- src/main/java/com/aptner/v3/board/comment/CommentService.java
- src/main/java/com/aptner/v3/board/common/reaction/ReactionRepository.java
> [hotfix] 댓글 오류

- src/main/java/com/aptner/v3/board/comment/CommentService.java
> [댓글 오류] reaction 검색 오류 ( illegalstatement)

- src/main/java/com/aptner/v3/attach/service/AttachService.java
- src/main/java/com/aptner/v3/board/common_post/CommonPostController.java
- src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
- src/main/java/com/aptner/v3/board/complain/dto/ComplainDto.java
- src/main/java/com/aptner/v3/board/free_post/dto/FreePostDto.java
- src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
- src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostController.java
- src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
- src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
- src/main/java/com/aptner/v3/board/qna/dto/QnaDto.java
- src/main/java/com/aptner/v3/global/util/MultipartUtil.java
[여기에 변경 내용에 대한 간단한 설명을 작성해주세요.]
[만약 PR을 검토하는 동안 주의해야 할 사항이 있다면 여기에 작성해주세요.]
목록조회
```
curl -X 'GET' \
'http://localhost:82/boards/frees?category-id=0&limit=10&page=1&sort=RECENT' \
-H 'accept: application/json;charset=UTF-8'
----------
{
"id": 134,
"user_id": 3,
"user_nickname": "nick3",
"user_image": "https://avatars.githubusercontent.com/u/79270228?s=80&v=4",
"category_name": "교육/육아",
"title": "test0611_2",
"content": "test0611test0611test0611",
"image_urls": [
"https://aptners.s3.ap-southeast-1.amazonaws.com/file/53ffadea-d963-492d-8916-e352add00ae2/300.jpeg",
"https://aptners.s3.ap-southeast-1.amazonaws.com/file/b4299f1c-05dc-4bd3-b293-a777d042fdcd/300.png"
],
"visible": true,
"reaction_columns": {
"count_reaction_type_good": 0,
"count_reaction_type_bad": 0
},
"count_of_comments": 3, …
```
> [이미지 리사이즈]
